<?php

namespace AppBundle\Repository;

/**
 * ChannelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChannelRepository extends \Doctrine\ORM\EntityRepository
{
	public function getChannelsByUser($userId)
	{
		$query = $this->createQueryBuilder('c')
			->innerJoin('c.users', 'u', 'WITH', 'u.id = :id')
			->setParameter('id', $userId)
			->getQuery();
		return $query->getResult();
	}
}
