app:
    resource: "@AppBundle/Controller/"
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

login:
    path:   /login
    defaults:  { _controller: AppBundle:Security:login }

login_check:
    path:   /login_check

